### ISSUE TITLE
v3.18.0-specific issue running CWL with singularity

### ISSUE THREAD

**Issue by KerstenBreuer** [DataBiosphere/toil#2470]
After upgrading to toil 3.18.0 my CWL workflow, which uses singularity as containerization solution, failed with the following error:
``UnsupportedRequirement: Singularity implementation does not support custom networking``

When I downgrade to 3.17.0, everything works again.

As always I am very grateful for your competent and fast support.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-67)
┆Issue Number: TOIL-67

**Comment by mr-c** [comment]
Hello @KerstenBreuer , can you share your CWL workflow or tool?

**Comment by KerstenBreuer** [comment]
Hi, 
Yes sure thing. Here is the one command line tool that is causing the error:
```
cwlVersion: v1.0
class: CommandLineTool
requirements:
  InlineJavascriptRequirement: {}
  StepInputExpressionRequirement: {}
hints:
  ResourceRequirement:
    coresMin: 1
    ramMin: 5000
  DockerRequirement:
    dockerPull: kerstenbreuer/trim_galore:0.4.4_1.14_0.11.7
  
baseCommand: "fastqc"
arguments: 
  - valueFrom: $(runtime.outdir)
    prefix: "-o"
  - valueFrom: "--noextract"

inputs:
  fastq1:
    type: File?
    inputBinding:
      position: 1
  fastq2:
    type: File?
    inputBinding:
      position: 2
  bam:
    type: File?
    inputBinding:
      position: 1
 
outputs:
  fastqc_zip:
    doc: all data e.g. figures
    type:
      type: array
      items: File
    outputBinding:
      glob: "*_fastqc.zip"
  fastqc_html:
    doc: html report showing results from zip
    type:
      type: array
      items: File
    outputBinding:
      glob: "*_fastqc.html"
 ```

And here is a simplified version of the corresponding workflow:
```
cwlVersion: v1.0
class: Workflow

requirements:
  SubworkflowFeatureRequirement: {}
  ScatterFeatureRequirement: {}
  StepInputExpressionRequirement: {}
  InlineJavascriptRequirement: {}

inputs:
  fastq1:
    type: File
  fastq2: 
    type: File?
        
steps:
  qc_pre_trim:
    doc: fastqc - quality control for trimmed fastq
    run: "../tools/fastqc.cwl"
    in:
      fastq1:
        source: fastq1
      fastq2:
        source: fastq2
    out:
      - fastqc_zip
      - fastqc_html
      
outputs:
  pre_trim_fastqc_zip:
    type:
      type: array
      items: File
    outputSource: qc_pre_trim/fastqc_zip
  pre_trim_fastqc_html:
    type:
      type: array
      items: File
    outputSource: qc_pre_trim/fastqc_html    
```

To start, I use following command:
```
cwltoil --singularity --logDebug --clean always --cleanWorkDir always \
	my_workflow.cwl my_job_input.yaml
```

Thanks a lot for your help.
