### ISSUE TITLE
toil-cwl-runner doesn't generate a parameter via Javascript

### ISSUE THREAD

**Issue by alanhoyle** [DataBiosphere/toil#2722]
I'm trying to use the toil-cwl-runner (toil 3.20.0) on a workflow that works on both the reference cwl-runner and arvados-cwl-runner.  

One of the early steps is to run the GATK CreateSequenceDictionary on the reference FASTA and it appears that the Javascript embedded in the CWL is not adding the --OUTPUT parameter when it runs:  
```
cwlVersion: v1.0

class: CommandLineTool

label:  GATK/Picard CreateSequenceDictionary

doc: >
  A command Line tool to run the GATK/Picard CreateSequenceDictionary on a FASTA to make the .dict file for future use in other GATK/Picard contexts

requirements:
  DockerRequirement:
    dockerPull: broadinstitute/gatk
  InlineJavascriptRequirement: {}

hints:
  ResourceRequirement:
    coresMin: 2
    ramMin: 8000

baseCommand: [ '/gatk/gatk', 'CreateSequenceDictionary' ]

inputs:

  reference_fasta:
    type: File 
    inputBinding: 
      position: 1 
      prefix: --REFERENCE
      
  output_filename:
    type: [ "null", string ]
    inputBinding: 
      position: 2 
      prefix: --OUTPUT
      # needs to turn referenceFasta.fa to referenceFasta.dict
      valueFrom: |
        ${
           var name = inputs.reference_fasta.basename.replace(/fa$/, "dict").replace(/fasta$/, "dict");;
           return name;
           }
      
stdout: output.stdout.txt

outputs:
  fastaDict: 
    type: File
    outputBinding: 
      glob: "*.dict"

```

When I run with the toil-cwl-runner, I see this:

```
WARNING:toil.leader:T/e/jobz5qCdm        /gatk/gatk \
WARNING:toil.leader:T/e/jobz5qCdm        CreateSequenceDictionary \
WARNING:toil.leader:T/e/jobz5qCdm        --REFERENCE \
WARNING:toil.leader:T/e/jobz5qCdm        /var/lib/cwl/stg89963c4c-203f-4501-b1d5-5b04b02d3a94/GRCh38.d1.vd1.fa > /scratch/tmp1MaRUB/4/2/out_tmpdirRwJQ5n/output.stdout.txt
WARNING:toil.leader:T/e/jobz5qCdm    Using GATK jar /gatk/gatk-package-4.1.2.0-local.jar
```
by contrast, when I run this in Arvados, I see this:
```
[
   "/gatk/gatk",
   "CreateSequenceDictionary",
   "--REFERENCE",
   "/keep/728245198951799caaa78bb663e4efc5+2006/GRCh38.d1.vd1.fa",
   "--OUTPUT",
   "GRCh38.d1.vd1.dict"
 ]
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-387)
┆Issue Number: TOIL-387

**Comment by mr-c** [comment]
Can you try `valueFrom: $(inputs.reference_fasta.nameroot).dict` ? That doesn't need `InlineJavascriptRequirement`

**Comment by mr-c** [comment]
Probably not showing up because it is an optional input. I would move it to the arguments section, as you aren't even using the value of `output_filename`:


```
arguments:
  - position: 2
    prefix: --OUTPUT
    valueFrom: $(inputs.reference_fasta.nameroot).dict 
```
