### ISSUE TITLE
toil-cwl-runner doesn't respect the `^` symbol in secondaryFiles

### ISSUE THREAD

**Issue by alexiswl** [DataBiosphere/toil#3190]
If I have the following input for a cwltool,

```yaml
inputs:
  fasta_reference:
    type: File
    secondaryFiles:
      - ".fai"
      - "^.dict"
```  

where my reference name is `hg38.fa` with the secondary files, `hg38.fa.fai` and `hg38.dict`, these are not respected by toil-cwl-runner command, as it seems to be looking for the literal "^.dict"

Reproducible example to come.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-632)
┆Issue Number: TOIL-632

**Comment by alexiswl** [comment]
```
$ toil-cwl-runner --version
4.2.0
```

```
$ cwltool --version
cwltool 3.0.20200709181526
```

**Comment by DailyDreaming** [comment]
@mr-c Do you know what test would cover this in the conformance tests?

**Comment by arostamianfar** [comment]
FWIW, we have been successfully using `^.dict` in our workflows. @alexiswl not sure if anything is different in your workflow, but would be good to share an e2e example. It may just be an issue with the filenames.

For reference, here's our workflow that returns a reference as the output, which is then passed as inputs to other tasks:
```
outputs:
  reference:
    type: File
    outputBinding:
      glob: $('myref.fa')
    secondaryFiles:
      - .fai
      - ^.dict
```
