### ISSUE TITLE
Double Mem functionality with batch schedulers toil-cwl-runner

### ISSUE THREAD

**Issue by drkennetz** [DataBiosphere/toil#3269]
Referencing #2042 here. This is less of an issue and more of an enhancement. On batch systems such as HPC environments, it would be incredibly helpful to have a `--doublemem` flag for workflows. 

In short, the doublemem flag would be passed at runtime on the first instantiation of the workflow. This flag would tell toil to capture failure reasons of jobs, and if the failure reason corresponded to a TERM_MEMLIMIT or TERM_ENOMEM, the specific step that failed would be retried with double the initial requested memory. This would be helpful for genomics workflows with specific steps that did not have well-defined memory profiles (I think most commonly seen with Structural Variants or even STAR).

An example of this would be something like:
```
steps:
  bwa:
    requirements:
      ResourceRequirement:
        ramMax: 5000
...
```
This would likely fail on about 50% of bwa jobs because bwa can use anywhere from 4-10G depending on samples / version of bwa. by running this with `--doublemem`, this would capture failures due to TERM_MEMLIMIT (this might be LSF specific), so for your 50% of failed jobs, they would automatically be restarted with 10G, making the section look like:
```
steps:
  bwa:
    requirements:
      ResourceRequirement:
        ramMax: 10000
...
```
Do you guys have thoughts on this?

Thanks,
Dennis

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-689)
┆Issue Number: TOIL-689
