### ISSUE TITLE
Run CWL conformance tests on Kubernetes.

### ISSUE THREAD

**Issue by DailyDreaming** [DataBiosphere/toil#3325]
Just creating an issue for: https://github.com/DataBiosphere/toil/pull/3323  I believe the title is straight forward.

Currently my suspicion is that this is failing (`11 tests passed, 186 failures, 0 unsupported features`) due to misconfigured credentials: https://ucsc-ci.com/databiosphere/toil/-/jobs/65246

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-726)
┆Issue Number: TOIL-726

**Comment by adamnovak** [comment]
I can run the tests manually. I make this pod:

```
kubectl --namespace toil delete pod adamnovak-pod
kubectl --namespace toil apply -f - <<'EOF'
apiVersion: v1
kind: Pod
metadata:
  name: adamnovak-pod
spec:
  containers:
  - name: anovak-container
    image: quay.io/ucsc_cgl/toil:5.1.0-py3.7
    imagePullPolicy: Always
    env:
    args: ["sleep", "infinity"]
    resources:
      requests:
        cpu: 4000m
        memory: "4Gi"
        ephemeral-storage: "10Gi"
      limits:
        cpu: 4000m
        memory: "4Gi"
        ephemeral-storage: "10Gi"
    volumeMounts:
      - mountPath: /scratch
        name: scratch
      - mountPath: /root/.aws
        name: s3-credentials
  restartPolicy: Never
  volumes:
  - name: scratch
    emptyDir: {}
  - name: s3-credentials
    secret:
      secretName: shared-s3-credentials
  serviceAccountName: toil-svc
EOF
```

And then I go into it:

```
kubectl --namespace toil exec -ti adamnovak-pod -- /bin/bash
```

And then I run all this (noting that the `apt-get` lines will swallow subsequent input):

```
export TOIL_KUBERNETES_OWNER=toiltest
export TOIL_AWS_SECRET_NAME=shared-s3-credentials
export TOIL_KUBERNETES_HOST_PATH=/data/scratch
export TOIL_WORKDIR=/var/lib/toil
export SINGULARITY_CACHEDIR=/var/lib/toil/singularity-cache
mkdir -p ${TOIL_WORKDIR}

git clone https://github.com/DataBiosphere/toil.git
cd toil
git checkout releases/5.1.0

virtualenv --system-site-packages --python python3 venv
. venv/bin/activate


wget https://github.com/common-workflow-language/common-workflow-language/archive/6a955874ade22080b8ef962b4e0d6e408112c1ef.zip

apt-get update && apt-get install unzip -y

unzip 6a955874ade22080b8ef962b4e0d6e408112c1ef.zip

mv common-workflow-language-* src/toil/test/cwl/spec

pip install .[aws,cwl,kubernetes]
pip install cwltest

cd src/toil/test/cwl/spec/v1.0

'cwltest' '--tool=toil-cwl-runner' '--test=conformance_test_v1.0.yaml' '--timeout=2400' --basedir=`pwd`/src/toil/test/cwl/spec/v1.0 '--' '--disableCaching=True' '--clean=always' '--jobStore=aws:us-west-2:toil-test-6345-24837-9603' '--batchSystem=kubernetes'
    
```
