### ISSUE TITLE
CWL with batchSystem Slurm: This job was passed a promise that wasn't yet resolved when it ran.

### ISSUE THREAD

**Issue by elagina** [DataBiosphere/toil#3334]
Hello,

I am trying to run a very simple scatter workflow from  [CWL 1.2 conformance tests](https://github.com/common-workflow-language/cwl-v1.2/tree/main/tests) with `--batchSystem Slurm`
Here is workflow (cwlVersion changed to `v1.2.0-dev4` from `v1.2`):
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.2.0-dev4
class: Workflow
inputs:
  inp: string[]
outputs:
  out:
    type: string[]
    outputSource: step1/echo_out

requirements:
  - class: ScatterFeatureRequirement

steps:
  step1:
    in:
      echo_in: inp
    out: [echo_out]
    scatter: echo_in
    run:
      class: CommandLineTool
      inputs:
        echo_in:
          type: string
          inputBinding: {}
      outputs:
        echo_out:
          type: string
          outputBinding:
            glob: "step1_out"
            loadContents: true
            outputEval: $(self[0].contents)
      baseCommand: "echo"
      arguments:
        - "-n"
        - "foo"
      stdout: "step1_out"
```
Here is `toil-cwl-runner` command:
```
toil-cwl-runner \
    --logLevel DEBUG \
    --enable-dev \
    --batchSystem Slurm \
    --workDir /tmp \
    cwl-v1.2-main/tests/scatter-wf1.cwl \
    cwl-v1.2-main/tests/scatter-job1.json
```
and this is the error I get only when using `--batchSystem Slurm` (finishes successfully without it)
```
    "this job as a child/follow-on of {jobName}.".format(jobName=jobName))
RuntimeError: This job was passed a promise that wasn't yet resolved when it ran. 
The job 'CWLGather' that fulfills this promise hasn't yet finished. 
This means that there aren't enough constraints to ensure the current job always runs after 'CWLGather'. 
Consider adding a follow-on indirection between this job and its parent, 
or adding this job as a child/follow-on of 'CWLGather'.
```

```
toil = 4.2.0
cwltool = 3.0.20200709181526
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-730)
┆Issue Number: TOIL-730
