### ISSUE TITLE
Leverage CWL's support for streaming inputs/outputs

### ISSUE THREAD

**Issue by mr-c** [DataBiosphere/toil#3469]
Command line scientific analysis tools often support streaming data into or out of the tool. (At the command line we use the unix pipe “|” or named pipes to implement this). This speeds up the analysis by avoiding slow disk/storage IO.

While the CWL standard supports this approach, no CWL-aware workflow system makes use of this optimization.

The first iteration would stream in and out of object stores (Amazon S3, Google Cloud Storage, etc..). More advanced implementations may feature direct streaming between the tools, but this requires refactoring the job scheduling engine.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-811)
┆Issue Number: TOIL-811

**Comment by mr-c** [comment]
@adamnovak @DailyDreaming or anyone else available to co-mentor this, please indicate so at [the OBF GSoC ideas document](ttps://docs.google.com/document/d/1kPf-fLDmjoVGf7TvbOB6H12pC_s_y_5TUGiKAxre64M/edit#bookmark=id.wgkcqzuh5vjt) ; thanks!

**Comment by kahanikaar** [comment]
@mr-c I would like to contribute to the project Distributed workflow execution with data streaming (Common Workflow Language project / Toil) for GSoC'2021, will be grateful for guidance to approach this.

**Comment by DailyDreaming** [comment]
@kahanikaar @mr-c I can help mentor this.

The first step would be setting up and installing `Toil` from source: https://toil.readthedocs.io/en/latest/gettingStarted/install.html#building-from-source

Then successfully running a CWL workflow with `Toil`: https://toil.readthedocs.io/en/latest/gettingStarted/quickStart.html#running-a-basic-cwl-workflow

Then setting up an example workflow that uses streaming and successfully running it with `cwltool`: https://www.biostars.org/p/229095/#230278

Finally, attempting to run the example workflow in `Toil` to see where it fails and which `cwltool` library or params need to be added for the feature to be supported.  This should be done with `Toil`'s `--debugWorker` flag and stepped through using a debugger to find where `Toil`'s and `cwltool`'s behavior diverge.

This is because `Toil` uses `cwltool` to run CWL workflows by importing it's libraries: https://github.com/DataBiosphere/toil/blob/master/src/toil/cwl/cwltoil.py#L51-L77  So adding support should involve figuring out how to use the appropriate `cwltool` library to enable the reciprocal behavior in `Toil`.

Let me know if you start work on this and have any questions.  It's usually helpful to take a look at the original PR in `cwltool` that added a feature as well, to get an idea of how it works and was intended to be used.  @mr-c Do you have a link handy to the PR that originally added this feature to cwl?

**Comment by karmadolkar** [comment]
Hello! I'm interested in the project as a GSoC'21 applicant. I set up `Toil` from source and ran the example CWL workflow with `Toil`.

While running the `cwltool` example on biostars, I ran into an issue and I had a few questions:

1. From what I could understand, the input to the yaml job is the workflow file (which in turn joins the wrappers together). Should the workflow file be named test.txt.gz?
2. Is this the block of code that implements streaming? Also, what does "streaming" mean?

```

  fileToSearch:
    type: File
    streamable: true
    inputBinding:
      position: 2

```
Is this included in the yaml job?

The command I'm running is `cwltool test.txt.gz example-job.yaml`. Any help/guidance would be much appreciated!

**Comment by DailyDreaming** [comment]
@karmadolkar So, I tried to find a better example for this and it seemed to work, so I might be missing what a good example is myself.

This was what I ran:

```
toil-cwl-runner stream.cwl stream.yml
```

Where `stream.cwl` is:

```
#!/usr/bin cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: cat
requirements:
  InlineJavascriptRequirement: {}

stdout: $(inputs.output_filename)
arguments: ["-A"]

inputs:
  input_file:
    type: File
    streamable: true
    inputBinding:
      position: 1
  output_filename:
    type: string?
    default: count.txt

outputs:
  count:
    type: stdout
```

And `stream.yml` is:

```
input_file:
  class: File
  path: s3://toil-datasets/hello.txt
```

@mr-c I believe that this works on the latest version of `toil`.  Is there a better example that could be tested or needs support?
