### ISSUE TITLE
CWL: missing documentation on conda dependency resolver

### ISSUE THREAD

**Issue by AriBad** [DataBiosphere/toil#3803]
Toil is used to run a pipeline written in cwl on HPC (using the --no-container flag).The pipeline specifies software requirements for some tools and their versions. However, Toil doen't take into acount this requirements and crashes when running the pipeline. 
Here is  a minimal exemple of the problem:
````
class: CommandLineTool
cwlVersion: v1.0
doc: ""
hints:
  - class: DockerRequirement
    dockerPull: quay.io/biocontainers/drep:3.2.2--pyhdfd78af_0
  - class: SoftwareRequirement
    packages:
      drep:
        specs: 
          - https://anaconda.org/bioconda
        version:
          - "3.2.2=pyhdfd78af_0"

requirements:
  - class: InlineJavascriptRequirement

inputs:
  work_directory:
    type: string
    doc: |
      name of output/work directory
    inputBinding:
      position: 1
    default: "drep_out"

  genomes:
    type: File[]
    doc: |
      genomes to filter in .fasta format
    inputBinding:
      position: 2
      prefix: --genomes

outputs:
  output_directory:
    type: Directory
    outputBinding:
      glob: $(runtime.outdir)/$(inputs.work_directory)

baseCommand:
  - dRep
  - dereplicate 

````
And I have this error :

````
[cwltool] 'dRep' not found: [Errno 2] No such file or directory: 'dRep'
[...]
[toil.worker] Exiting the worker because of a failed job on host zonda20.plafrim.cluster
````

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1032)
┆Issue Number: TOIL-1032
