### ISSUE TITLE
toil-cwl-runner is missing the "path" output field on local executions for Files and Directories.  

### ISSUE THREAD

**Issue by kannon92** [DataBiosphere/toil#3870]
Hi, I noticed a minor difference between cwltool and toil-cwl-runner.

If I run a simple hello world and capture the stdout, I notice that the output is different from cwltool to toil.

cwltool:
```
"echoOut": {
"location": "file:///Users/kevinhannon/Work/GIT/slurm-compute/src/tests/data/doubles/echo.out",
"basename": "echo.out",
"class": "File",
"checksum": "sha1$0ecb65b12a43095690182b0c2a3152211b4292d3",
"size": 12,
"path": "/Users/kevinhannon/Work/GIT/slurm-compute/src/tests/data/doubles/echo.out"
}
```
toil-cwl-runner:
```
"echoOut": {
    "location": "file:///Users/kevinhannon/Work/GIT/slurm-compute/src/__tests__/data/doubles/echo.out",
    "basename": "echo.out",
    "nameroot": "echo",
    "nameext": ".out",
    "class": "File",
    "checksum": "sha1$0ecb65b12a43095690182b0c2a3152211b4292d3",
    "size": 12
}
```
There seems to be a few differences but the "path" field is missing from toil-cwl-runner. I am using the latest release of toil (5.5.0).  

The command line tool that can reproduce this problem:

```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: [echo]
stdout: "echo.out"
inputs: 
  message: 
    type: string
    inputBinding:
      position: 1
outputs: 
  echoOut:
    type: stdout
```

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1063)
┆Issue Number: TOIL-1063
