### ISSUE TITLE
Job names for HPC schedulers should be reflect the workflow and step name.  

### ISSUE THREAD

**Issue by kannon92** [DataBiosphere/toil#3884]
We are calling toil via a rest api and submitting our workflows to a slurm cluster. I would like to be able to monitor individual steps of the workflow but I don't know how I can know ahead of time what the name of the job would be. I was hoping to use squeue or sacct to get the status of each step of the workflow.

For our cloud platform, we use the id of the workflow and we can queue Argo to get status of each step of the workflow.

The current name of a toil job from a workflow would be toil_job_{id}_CWLJob.  

The hope is to be able to use a HPC cli to query the status of the job but we don't really know what job id corresponds to what job.  So I am hoping to change the default JobName so that we can check the status of jobs in a workflow.  

For the below workflow,

```
cwlVersion: v1.0
class: Workflow
id: echo-sleep
inputs:
  echoMessage: string
  sleepParam: int
outputs: {}
steps:
  echo:
    run: echo.cwl
    in:
      hello: echoMessage
    out: []
  sleep:
    run: sleep.cwl
    in:
      sleepTime: sleepParam
    out: []
 ```

The echo step would be toil_job_2_echo-sleep.echo.
 
The sleep step would be toil_job_3_echo-sleep.sleep.  
 
Talking with @mr-c, it sounds like the intent of https://github.com/DataBiosphere/toil/blob/master/src/toil/cwl/cwltoil.py#L1862 was to give a more descriptive name to the individual jobs.  But this looks to not work.  The name reflects the name of the class.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1072)
┆Issue Number: TOIL-1072
