### ISSUE TITLE
ResourceRequirement of CWL file is ignored when CommandLineTool is run from the Workflow.

### ISSUE THREAD

**Issue by michael-kotliar** [DataBiosphere/toil#3920]
When submitting the following CWL `CommandLineTool` on LSF with Toil 5.5.0 I can see that the node has been requested with the proper memory and cpu parameters.
```yaml
cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
requirements:
  ResourceRequirement:
    ramMax: 1048576  # in KB
    coresMax: 4
stdout: output.txt
inputs:
  message:
    type: string
    inputBinding:
      position: 1
outputs:
  output:
    type: stdout
```
However, when I use this `CommandLineTool` as a workflow step, the `ResourceRequirement` field is completely ignored, even after I explicitly add it almost everywhere: global for the Workflow, additionally for the step.
```cwl
cwlVersion: v1.1
class: Workflow

requirements:
  ResourceRequirement:
    ramMax: 1048576  # in KB
    coresMax: 4

inputs:
  message:
    type: string
outputs:
  output:
    type: File
    outputSource: echo/output
steps:
  echo:
    run: ./tool.cwl
    requirements:
      ResourceRequirement:
        ramMax: 1048576  # in KB
        coresMax: 4
    in:
      message: message
    out: [output]
```
