### ISSUE TITLE
A scatter workflow that collects stdout and stderr will only output one log file.

### ISSUE THREAD

**Issue by kannon92** [DataBiosphere/toil#3960]
If you try to capture stdout and stderr logs in a plugin that is also using scatter, you will only get 1 log file.

workflow
```
cwlVersion: v1.0
class: Workflow
requirements:
  ScatterFeatureRequirement: {}
inputs: 
  message: string[]
outputs: 
  echoStdOut:
    type: File[]
    outputSource: ["echo/echoOut"]
steps:
  echo:
    run: echo.cwl
    scatter: message
    in: 
      message: message
    out: [echoOut]
```

echo.cwl

```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: [echo]
id: "echo"
inputs: 
  message: 
    type: string
    inputBinding:
      position: 1
outputs: 
  echoOut:
    type: stdout
    
```

You can pass a string array for inputs.  

Since I do not specify the name of the file, you will get a random UUID for the stdout log file.  Cwltool will actually generate three separate files:

```
{
    "echoStdOut": [
        {
            "location": "file:///Users/kevinhannon/Work/GIT/common-workflow-fun/Templates/hello-sleep/f031a820abddc1087099df218c569132c8a19dc0",
            "basename": "f031a820abddc1087099df218c569132c8a19dc0",
            "class": "File",
            "checksum": "sha1$f572d396fae9206628714fb2ce00f72e94f2258f",
            "size": 6,
            "path": "/Users/kevinhannon/Work/GIT/common-workflow-fun/Templates/hello-sleep/f031a820abddc1087099df218c569132c8a19dc0"
        },
        {
            "location": "file:///Users/kevinhannon/Work/GIT/common-workflow-fun/Templates/hello-sleep/f031a820abddc1087099df218c569132c8a19dc0_2",
            "basename": "f031a820abddc1087099df218c569132c8a19dc0",
            "class": "File",
            "checksum": "sha1$63bbfea82b8880ed33cdb762aa11fab722a90a24",
            "size": 5,
            "path": "/Users/kevinhannon/Work/GIT/common-workflow-fun/Templates/hello-sleep/f031a820abddc1087099df218c569132c8a19dc0_2"
        },
        {
            "location": "file:///Users/kevinhannon/Work/GIT/common-workflow-fun/Templates/hello-sleep/f031a820abddc1087099df218c569132c8a19dc0_3",
            "basename": "f031a820abddc1087099df218c569132c8a19dc0",
            "class": "File",
            "checksum": "sha1$8af88d48ec099be3a1329b936c88e6518f04c731",
            "size": 6,
            "path": "/Users/kevinhannon/Work/GIT/common-workflow-fun/Templates/hello-sleep/f031a820abddc1087099df218c569132c8a19dc0_3"
        }
    ]
}
```

toil-cwl-runner will just generate one file and it is the same.  Its the last write that gets saved and outputted.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1109)
┆friendlyId: TOIL-1109
