### ISSUE TITLE
Job never stop with javascript input

### ISSUE THREAD

**Issue by EtiennePer** [DataBiosphere/toil#3965]
Hello there, 
we are facing an issue with a workflow that is using this type of CWL file: 

the problem appear only when i'm using "InlineJavascriptRequirement" with this kind of javascript expressions :
```YAML
my_step:
    run: ./my_sub_cwl.cwl
    in:
      # Javascript sub selection
      array_input:
        source: array_input
        valueFrom: |
          ${
            for (var i = 0 ; i < self.length; i++) {
              if ( self[i].basename.includes("<here I'm putting any string in order to filter>")) {
                return self[i]
              }
            }
            return self[0]
          }
     
    out: [ out1, out2]
```

I also tried another notation, but the exact same issue appears: 
```YAML
valueFrom: $(inputs.array_input.filter(f => f.basename.includes("<here I'm putting any string in order to filter>"))[0])
```

The actual task is **finishing correctly** (with a return_code = 0 ), the input File generated by the Javascript expression is properly set and the file is retrieved.

**BUT**

The job never "finished" properly and loop over this message infinitely : 
**`[2021-12-16T14:48:28+0000] [Thread-2  ] [W] [toil.batchSystems.singleMachine] Sent redundant job completion kill to surviving process group 615 known to batch system 140180515079744
`**

**Important note :**

1. We were not facing this issue with toil **v5.3.0** but only after updating to **v5.5.0** (we didn't tried with 5.4.0)
2. I'm not facing the issue if I use the following expression : `valueFrom: $(self[0])`

I did not found any similar issue for now, and don't know what to try in order to fix it. 

Any help would be really helpful.

Thanks a lot in advance :) ,
Etienne

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1110)
┆friendlyId: TOIL-1110
