### ISSUE TITLE
CWL Conditional steps that aren't running still get scheduled to a job scheduler.

### ISSUE THREAD

**Issue by kannon92** [DataBiosphere/toil#3990]
When I use conditionals, I find that the job still gets scheduled to a batch system.  

conditional-workflow.cwl

```
class: Workflow
cwlVersion: v1.2
inputs:
  message: string
  sleepParam: int 
outputs:
  out1:
    type: File
    outputSource:
      - echo/echoOut
    pickValue: first_non_null

requirements:
  InlineJavascriptRequirement: {}

steps:
  echo:
    in: 
      message: message
      sleepParam: sleepParam
    run: echo.cwl
    out: [echoOut]
    when: $(inputs.sleepParam > 1)
```

echo.cwl

```
cwlVersion: v1.2
class: CommandLineTool
baseCommand: [echo]
id: "echo"
inputs: 
  message: 
    type: string
    inputBinding:
      position: 1
outputs: 
  echoOut:
    type: stdout
```
param.yaml
```
sleepParam: 1
message: hello
```
When I run this workflow, you can see in the log files that the job gets issued.  For HPC systems, it does look like the job gets scheduled on a HPC cluster.  

[2022-01-07T09:39:12-0500] [MainThread] [I] [toil.leader] Issued job 'CWLJob' echo-sleep-conditional.cwl.echo.echo kind-CWLJob/instance-e9x_ed10 v1 with job batch system ID: 1 and cores: 1, disk: 3.0 Gi, and memory: 2.0 Gi

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/TOIL-1121)
┆friendlyId: TOIL-1121
