### ISSUE TITLE
toil-cwl-runner: bail out when --bypass-file-store not given for in-place update workflow

### ISSUE THREAD

**Issue by gmloose** [DataBiosphere/toil#4335]
When using `toil-cwl-runner` to execute a workflow that uses the `InplaceUpdateRequirement`, it should bail out with an error if the command-line option `--bypass-file-store` is not given. 

The problem is that, if you forget this option, `toil-cwl-runner` will run to completion without error, but it will _not_ have updated the input file in-place.

This can easily be tested with the following workflow:
```
cwlVersion: v1.2
class: CommandLineTool

baseCommand: bash

arguments:
 - -c
 - 'echo extra >> $(inputs.input_file.path)'

inputs:
  input_file: File

outputs:
  output_file:
    type: File
    outputBinding:
      outputEval: $(inputs.input_file)

hints:
  - class: DockerRequirement
    dockerPull: 'ubuntu:latest'
  - class: InplaceUpdateRequirement
    inplaceUpdate: true

requirements:
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.input_file)
        writable: true
```
Execute the workflow as follows, and check the contents of `hello.txt` afterwards.
```
echo "Hello World" > hello.txt
toil-cwl-runner try.cwl --input_file hello.txt
cat hello.txt
```
You would expect that `hello.txt` would now contain two lines (the second reading "extra"), but it doesn't.
Think work correctly if you add the command-line option `--bypass-file-store`.
