### ISSUE TITLE
`loadContents` option for WorkflowInputParameter does not add `contents` field to File object

### ISSUE THREAD

**Issue by npilshchikova** [DataBiosphere/toil#4574]
There are a step with `loadContents` option in CWL v1.2 Worflow, such as:

```
cwlVersion: v1.2
class: Workflow

steps:
...
  do_stuff:
    run: my_tool.cwl
    when: $(inputs.read_count > 0)
    in:
      read_count:
        source: previous_step/read_count
        loadContents: true
        valueFrom: |
          $(parseInt(self.contents.replace(/\s+$/g, '')))
    out: [output_file]
...
```

From CWL documentation, following behavior is expected:

> If true, the file (or each file in the array) must be a UTF-8 text file 64 KiB or smaller, and the implementation must read the entire contents of the file (or file array) and place it in the contents field of the File object for use by expressions. If the size of the file is greater than 64 KiB, the implementation must raise a fatal error.

This workflow works correctly with cwltool==3.1.20230719185429, but with toil[cwl]==5.12.0 following error occurs:

```
cwl_utils.errors.WorkflowException: Expression evaluation error:
Expecting value: line 1 column 1 (char 0)
script was:
01 "use strict";
02 var inputs = {
11     "read_count": {
12         "location": "toilfile:7:1:files/for-job/kind-CWLJob/instance-7mv89nbf/file-22f5c9915c0946a2a6c792eb1d563a71/count.txt",
13         "basename": "count.txt",
14         "nameroot": "count",
15         "nameext": ".txt",
16         "class": "File",
17         "checksum": "sha1$c947175d684fa562f8d3332e037f2c1eef8080a1",
18         "size": 7,
19         "http://commonwl.org/cwltool#generation": 0
20     }
21 };
22 var self = {
23     "location": "toilfile:7:1:files/for-job/kind-CWLJob/instance-7mv89nbf/file-22f5c9915c0946a2a6c792eb1d563a71/count.txt",
24     "basename": "count.txt",
25     "nameroot": "count",
26     "nameext": ".txt",
27     "class": "File",
28     "checksum": "sha1$c947175d684fa562f8d3332e037f2c1eef8080a1",
29     "size": 7,
30     "http://commonwl.org/cwltool#generation": 0
31 };
32 var runtime = {
33     "tmpdir": null,
34     "outdir": null
35 };
36 (function(){return ((parseInt(self.contents.replace(/\s+$/g, ''))));})()
stdout was: ''
stderr was: 'evalmachine.<anonymous>:36
(function(){return ((parseInt(self.contents.replace(/\s+$/g, ''))));})()
                                            ^

TypeError: Cannot read property 'replace' of undefined
    at evalmachine.<anonymous>:36:45
    at evalmachine.<anonymous>:36:71
    at Script.runInContext (vm.js:133:20)
    at Script.runInNewContext (vm.js:139:17)
    at Object.runInNewContext (vm.js:322:38)
    at Socket.<anonymous> ([eval]:11:57)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at Socket.Readable.push (_stream_readable.js:224:10)'
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1387)
┆Issue Number: TOIL-1387
