### ISSUE TITLE
toil-cwl-runner doesn't handle defaults in the Hubmap Spatial Transcriptomics Pipeline

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4634]
If the default value [here](https://github.com/hubmapconsortium/spatial-transcriptomics-pipeline/blob/c47087d7f621126dbbc4aa232800457ecdec2d56/steps/spaceTxConversion.cwl#L74) is used in the `first_non_null` [here](https://github.com/hubmapconsortium/spatial-transcriptomics-pipeline/blob/c47087d7f621126dbbc4aa232800457ecdec2d56/steps/spaceTxConversion.cwl#L426-L428), Toil will fail and complain that it was null actually.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1424)
┆Issue Number: TOIL-1424

**Comment by adamnovak** [comment]
I'm not able to replicate this with this test workflow:
```
#!/usr/bin/env cwl-runner
cwlVersion: v1.2
class: Workflow
requirements:
  MultipleInputFeatureRequirement: {}
inputs:
  always_set:
    type: int?
    default: 0
  maybe_unset:
    type: int?
steps:
  main_step:
    run:
      class: CommandLineTool
      baseCommand: [echo]
      id: "echoInt"
      inputs: 
        message: 
          type: int
          inputBinding:
            position: 1
      outputs: 
        echoOut:
          type: stdout
    in:
      message:
        source: [always_set, maybe_unset]
        pickValue: first_non_null
    out: [echoOut]
outputs:
  result:
    type: File
    outputSource: main_step/echoOut
```

The 0 default value is getting picked up just fine.

**Comment by adamnovak** [comment]
I'm also not able to replicate the problem with this workflow that uses a non-running int-returning step to provide the first null:

```
#!/usr/bin/env cwl-runner
cwlVersion: v1.2
class: Workflow
requirements:
  MultipleInputFeatureRequirement: {}
  InlineJavascriptRequirement: {}
inputs:
  valueA:
    type: int?
    default: 0
  valueB:
    type: int?
  someFile:
    type: File?
steps:
  prev_step:
    run:
      class: ExpressionTool
      requirements:
        InlineJavascriptRequirement: {}
      inputs:
        someFile:
          type: File
      outputs:
        valueA:
          type: int
      expression: |
        ${
          return {valueA: 1};
        }
    in:
      someFile: someFile
    out: [valueA]
    when: $(inputs.someFile != null)
    
  main_step:
    run:
      class: ExpressionTool
      requirements:
        InlineJavascriptRequirement: {}
      inputs:
        valueA:
          type: int
      outputs:
        valueA:
          type: int
      expression: |
        ${
          return {valueA: inputs.valueA};
        }
    in:
      valueA:
        source: [prev_step/valueA, valueA]
        pickValue: first_non_null
    out: [valueA]
outputs:
  valueA:
    type: int
    outputSource: main_step/valueA
```
