### ISSUE TITLE
CWL output directories from task globs don't get their listings filled in when bypassing the file store

### ISSUE THREAD

**Issue by adamnovak** [DataBiosphere/toil#4698]
If I use this CWL:
```
cwlVersion: v1.2
class: CommandLineTool
requirements:
  MultipleInputFeatureRequirement: {}
  InlineJavascriptRequirement: {}
hints:
  DockerRequirement:
    dockerPull: docker.io/ubuntu:20.04
inputs:
  - id: tmp_prefix
    type: string
outputs:
  spaceTx_converted:
    type: Directory
    outputBinding:
      glob: $("tmp/" + inputs.tmp_prefix + "/2_tx_converted/")
baseCommand: [ bash, -c ]
arguments:
 - |
   mkdir -p $("tmp/" + inputs.tmp_prefix + "/2_tx_converted/");
   touch $("tmp/" + inputs.tmp_prefix + "/2_tx_converted/test.txt");
```
And I run it with `toil-cwl-runner --bypass-file-store --logDebug src/toil/test/cwl/glob_dir.cwl --tmp_prefix 12345`, then I get an output JSON without a listing, and 2_tx_converted in the current directory is not populated with its file after the workflow ends. If I drop --bypass-file-store, or if I use cwltool, I get a Directory at the end that actually has a listing showing the file, and the file seems to actually be made.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1455)
┆Issue Number: TOIL-1455
