### ISSUE TITLE
toil-cwl-runner fails unable to retrieve secondary files when --reference-inputs is on and and bash sh inside cwl

### ISSUE THREAD

**Issue by boyangzhao** [DataBiosphere/toil#4812]
toil version used: 6.1.0a1

When the `--reference-inputs` is turned on, it works fine generally when cwl is straightforward with secondary files defined in inputs and commands are defined in base command with args, etc. However, it seems when cwl uses input file requirements, with attached bash script, somehow the secondary files are not taken into account, and running toil-cwl-runner would fail.

Below is an example cwl, and with the error message (which indicates somehow secondary file is missing). This is only an issue when `--reference-inputs` is on.

*Example cwl*
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: ["/bin/bash", "bwa.sh"]
requirements:
    - class: DockerRequirement
      dockerPull: "<referring to a docker>"
    - class: InitialWorkDirRequirement
      listing:
      - entryname: 'bwa.sh'
        entry: |
            /opt/bwa mem "$3" "$1" "$2"
stdout: "out.bam"
inputs:
    fastq1:
        type: File
        inputBinding:
            position: 1
    fastq2:
        type: File
        inputBinding:
            position: 2
    reference:
        type: File
        secondaryFiles: [.amb, .ann, .bwt, .pac, .sa]
        inputBinding:
            position: 3
outputs:
    bam_out:
        type: File
        outputBinding:
            glob: '*.bam'
```

*Command ran*
`toil-cwl-runner --reference-inputs <cwl> <job yaml>`

*Error*
` ... [E::bwa_idx_load_from_disk] fail to locate the index files ...`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1509)
┆Issue Number: TOIL-1509

**Comment by adamnovak** [comment]
Your `.cwl` file would need to be coming from a URL and not from a path on the filesystem to trigger this, right? `--reference-inputs` is only supposed to do anything to inputs coming from URLs.

**Comment by adamnovak** [comment]
Oh, I read this again and it looks like the problem is that e.g. the `.amb` file is not getting downloaded and exposed to the container, when `--reference-inputs` is used?

**Comment by adamnovak** [comment]
I'm not able to replicate this with local files with a simple example that I think covers the important points.

I have a file `workflow.cwl`:
```
cwlVersion: v1.0
class: CommandLineTool
baseCommand: ["bash", "run.sh"]
requirements:
    - class: DockerRequirement
      dockerPull: "ubuntu:22.04"
    - class: InitialWorkDirRequirement
      listing:
      - entryname: 'run.sh'
        entry: |
            ls `dirname $1`
stdout: "out.out"
inputs:
    inFile:
        type: File
        inputBinding:
            position: 1
        secondaryFiles: [.second]
outputs:
    output_out:
        type: File
        outputBinding:
            glob: '*.out'
```

I also make some input files:
```
touch in.txt
touch in.txt.second
```

I run it like this:
```
toil-cwl-runner workflow.cwl --reference-inputs --inFile in.txt
```

And I get this when I `cat out.out`:
```
in.txt
in.txt.second
```

So the workflow is picking up the file from my filesystem even with `--reference-inputs`.
