### ISSUE TITLE
Add security context to Kubernetes batch system

### ISSUE THREAD

**Issue by xhejtman** [DataBiosphere/toil#5179]
Kubernetes clusters are moving to increased security through Pod Security Admission. It would be great, if this could be set as parameters so that K8s Jobs can run even in such restricted environments.

In particular, we need to set the Pod security context:
```
securityContext: 
  fsGroupChangePolicy: OnRootMismatch
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

and Container securityContext:

```
securityContext: 
  runAsUser: 1000
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
```

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TOIL-1686)
┆Issue Number: TOIL-1686
